services:
  backend:
    build: ./backend
    ports:
      - "3000:5000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:alpine
    command: redis-server --save "" --appendonly no
    ports:
      - "6379:6379"
    restart: unless-stopped
