export const mockProducts = [
  {
    _id: "mock-1",
    name: "Thanvi Glass Bangles Set",
    description: "Beautiful traditional maroon glass bangles with exquisite golden embellishments, perfect for festive occasions.",
    category: "Glass Bangles",
    price: 400,
    salePrice: 139,
    isOnSale: true,
    images: ["/thanvi-glass-bangles.jpg"],
    color: "Maroon",
    stock: 25
  },
  {
    _id: "mock-2",
    name: "Earthy Peacock Terracotta Set",
    description: "Traditional terracotta clay necklace and matching jhumka earrings set, handpainted in beautiful shades of blue and white.",
    category: "Jewellery Set",
    price: 699,
    salePrice: 499,
    isOnSale: true,
    images: ["https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=600&q=80"],
    color: "Blue-Green",
    stock: 12
  },
  {
    _id: "mock-3",
    name: "Velvet 3-Row Bangle Stand",
    description: "Keep your bangles organized and dust-free in this premium velvet-wrapped 3-tier stand.",
    category: "Organiser",
    price: 599,
    salePrice: 399,
    isOnSale: true,
    images: ["https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80"],
    color: "Red",
    stock: 15
  },
  {
    _id: "mock-4",
    name: "Festive Shubh Labh Gift Hamper",
    description: "A beautiful traditional gift box containing high-quality glass bangles, dry fruits, and a subh labh wall hanging.",
    category: "Hampers",
    price: 1499,
    salePrice: 999,
    isOnSale: true,
    images: ["https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=600&q=80"],
    color: "Red-Gold",
    stock: 8
  },
  {
    _id: "mock-5",
    name: "Anvi Glass Bangles",
    description: "Sleek red glass bangles with detailed sparkle accents, ideal for daily and celebratory wear.",
    category: "Glass Bangles",
    price: 200,
    salePrice: 139,
    isOnSale: true,
    images: ["https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=600&q=80"],
    color: "Red",
    stock: 30
  },
  {
    _id: "mock-6",
    name: "Jelly Ghungroo Bangles",
    description: "Fascinating purple translucent glass bangles adorned with delicate metallic ghungroo beads.",
    category: "Glass Bangles",
    price: 280,
    salePrice: 140,
    isOnSale: true,
    images: ["https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=600&q=80"],
    color: "Purple",
    stock: 15
  },
  {
    _id: "mock-7",
    name: "Handpainted Royal Jhumkas",
    description: "Grand terracotta temple style jhumkas highlighted in gold paint and red beads.",
    category: "Jumkas",
    price: 350,
    salePrice: 249,
    isOnSale: true,
    images: ["https://images.unsplash.com/photo-1635767798638-3e25273a8236?auto=format&fit=crop&w=600&q=80"],
    color: "Gold-Red",
    stock: 12
  },
  {
    _id: "mock-8",
    name: "Daily Wear Bangle Combo",
    description: "Convenient mix-and-match colorful glass bangles for everyday outfit styling.",
    category: "Combos",
    price: 500,
    salePrice: 350,
    isOnSale: true,
    images: ["https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=600&q=80"],
    color: "Mixed",
    stock: 20
  },
  {
    _id: "mock-9",
    name: "Earthy Leaf Clay Pendant",
    description: "Finely hand-carved leaf patterned pendant on adjustable thread necklace.",
    category: "Daily wear",
    price: 320,
    salePrice: 210,
    isOnSale: true,
    images: ["https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=600&q=80"],
    color: "Green-Brown",
    stock: 15
  },
  {
    _id: "mock-10",
    name: "Wooden Jewellery Storage Chest",
    description: "Beautiful solid wood jewellery organiser box featuring brass latch detail and velvet compartments.",
    category: "Organiser",
    price: 1200,
    salePrice: 899,
    isOnSale: true,
    images: ["https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80"],
    color: "Mahogany",
    stock: 10
  },
  {
    _id: "mock-11",
    name: "Royal Bangle Gift Box Hamper",
    description: "Luxury velvet box featuring two sets of traditional glass bangles and a customized greeting card.",
    category: "Hampers",
    price: 1800,
    salePrice: 1299,
    isOnSale: true,
    images: ["https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=600&q=80"],
    color: "Maroon-Gold",
    stock: 10
  },
  {
    _id: "mock-12",
    name: "Aarvi Glass Bangles",
    description: "Charming red glass bangles featuring thin spiral gold lines, perfect for pairing with ethnic attire.",
    category: "Glass Bangles",
    price: 250,
    salePrice: 125,
    isOnSale: true,
    images: ["https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=600&q=80"],
    color: "Red",
    stock: 35
  },
  {
    _id: "mock-13",
    name: "Diya Glass Bangles",
    description: "Stunning teal Ramar blue glass bangles detailed with premium beads and kundan stones.",
    category: "Glass Bangles",
    price: 299,
    salePrice: 99,
    isOnSale: true,
    images: ["https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=600&q=80"],
    color: "Teal Blue",
    stock: 14
  },
  {
    _id: "mock-14",
    name: "Traditional Temple Jhumkas",
    description: "Traditional terracotta temple style jhumkas highlighted in gold paint and red beads.",
    category: "Jumkas",
    price: 350,
    salePrice: 249,
    isOnSale: true,
    images: ["https://images.unsplash.com/photo-1635767798638-3e25273a8236?auto=format&fit=crop&w=600&q=80"],
    color: "Gold-Red",
    stock: 12
  },
  {
    _id: "mock-15",
    name: "Gold Glaze Clay Studs",
    description: "Elegant black clay studs glazed with premium metallic gold borders.",
    category: "Studs",
    price: 160,
    salePrice: 110,
    isOnSale: true,
    images: ["https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=600&q=80"],
    color: "Gold-Black",
    stock: 18
  },
  {
    _id: "mock-16",
    name: "Traditional Mango Mala Set",
    description: "Clay-crafted Mango design traditional South Indian design necklace and hangings.",
    category: "Jewellery Set",
    price: 999,
    salePrice: 799,
    isOnSale: true,
    images: ["https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=600&q=80"],
    color: "Gold-Red",
    stock: 9
  },
  {
    _id: "mock-17",
    name: "Grand Terracotta Bridal Set",
    description: "Ornate multi-layered handcrafted terracotta necklace set detailed with gold and maroon paint.",
    category: "Bridal Set",
    price: 1999,
    salePrice: 1499,
    isOnSale: true,
    images: ["https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=600&q=80"],
    color: "Maroon-Gold",
    stock: 5
  },
  {
    _id: "mock-18",
    name: "Little Princess Clay Pendant",
    description: "Cute, small baby pink elephant clay pendant set for kids.",
    category: "Kids wear",
    price: 199,
    salePrice: 120,
    isOnSale: true,
    images: ["https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=600&q=80"],
    color: "Pink-Yellow",
    stock: 25
  },
  {
    _id: "mock-19",
    name: "Portable Travel Bangle Box",
    description: "Hard-shell velvet-padded travel organiser for bangles and watches.",
    category: "Organiser",
    price: 350,
    salePrice: 249,
    isOnSale: true,
    images: ["https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80"],
    color: "Pink Velvet",
    stock: 18
  },
  {
    _id: "mock-20",
    name: "Baby Shower Gifting Hamper",
    description: "Special gifting pack filled with baby shower glass bangles, clay matching studs, and sweet treats.",
    category: "Hampers",
    price: 2200,
    salePrice: 1699,
    isOnSale: true,
    images: ["https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=600&q=80"],
    color: "Multi-color",
    stock: 5
  }
];
